apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "s3-balance.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "s3-balance.labels" . | nindent 4 }}
data:
  config.yaml: |{{ .Values.config.configYaml | nindent 4 }}