apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "s3-balance.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "s3-balance.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}