apiVersion: v1
kind: Service
metadata:
  name: s3-balance-service
  namespace: s3-balance
  labels:
    app: s3-balance
spec:
  selector:
    app: s3-balance
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: s3-balance-metrics-service
  namespace: s3-balance
  labels:
    app: s3-balance
    service-type: metrics
spec:
  selector:
    app: s3-balance
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: metrics
  type: ClusterIP